#+title: main.org

* Science Background

** Types of Waves 

Mechanical waves are waves that require a medium, or material, for transmission. The medium may be a gas, liquid, or solid. Mechanical waves get their energy from a vibrating source, such as a tuning fork or a boat’s propeller. The energy temporarily displaces molecules of the medium and is passed on to other particles through collisions. For example, a vibrating tuning fork causes the air molecules around it also to vibrate. The vibrating molecules pass their energy to nearby molecules, creating a sound wave. Although the molecules are temporarily displaced as they gain energy, they return to their original positions as the wave passes. Thus, the wave passes through a medium, but the medium itself does not travel along with the wave as energy is transmitted. 

Electromagnetic waves include visible light as well as infrared and ultraviolet light, microwaves, X-rays, and gamma rays. These waves are generated by oscillations of electrical and magnetic fields from charged particles and do not need a medium. In fact, they travel fastest in a vacuum and slow down when they enter a medium. All electromagnetic waves in a vacuum move at the same speed. This speed, 3 × 108 m/s, is known as the speed of light and is represented by the letter c. 

** Wave Shapes 

A transverse wave is a wave that displaces particles of its medium perpendicular to the wave’s direction of  
travel. A wave on the surface of a lake is an example of a transverse wave. A girl floating on a raft moves  
up and down as the wave passes. She then returns to her starting position once the wave has gone by.  
Light waves and other electromagnetic radiation are transmitted only as transverse waves. 

Transverse waves contain crests (high points) and troughs (low points). The distance from one crest to the  
next is the wavelength (λ). The height of a transverse wave, measured from the middle line to a crest, is its  
amplitude. Amplitude can also be measured from the middle line to a trough. 

A longitudinal or compression wave is a wave that vibrates molecules back and forth in a direction 
parallel to the wave’s direction of travel. This parallel vibration creates a temporary compacting of particles  
(compression) and spreading out of particles (rarefaction). A way to model a longitudinal wave is to  
use a coiled spring connected to an immoveable object. As a person moves the free end of the spring back and  
forth rapidly in a straight line, a compression wave travels down the length of the spring. 

The wavelength of a longitudinal wave is the distance from one compression to the next, measured center  
to center. The amplitude of a longitudinal wave is a measure of how compact the compressions are. A wave  
in which the medium is very compressed and then very spread out has a large amplitude.

** Seismic waves 

Seismic waves are mechanical waves in the earth that are caused by earthquakes or volcanic activity. They  
are unique in that they may be either transverse or longitudinal. Seismic waves are classified as either  
surface waves or as body waves that occur deep within the earth. 

Primary waves (P waves) are the first waves to be felt after an earthquake. P waves are body waves and travel from inside the earth toward the outside. They can move quickly through rock, liquid, or air and can reach the opposite side of Earth in as few as 20 minutes. P waves are longitudinal waves, shaking the medium back-and-forth parallel to the direction of movement of wave energy. 

Shear waves (S waves) are body waves that can move 
from side to side (S-Horizontal, SH) or up and down  
(S-Vertical, SV) . In both cases, particle movement is  
perpendicular to the direction of energy transmission, 
which means that shear waves are examples of transverse  
waves . Shear waves move only through solid rock and are  
much slower than primary waves . Geologists commonly 
call shear waves “secondary waves .” 

As P and S waves from an earthquake reach Earth’s  
surface, they generate surface waves known as Love 
waves and Rayleigh waves . A Love wave is a surface  
transverse wave, moving side-to-side perpendicular 
to the direction of wave energy . A Rayleigh wave is a  
slower wave that resembles an ocean wave . The ground  
rolls up and down as the wave moves forward in a  
given direction . If you were to view Rayleigh waves  
approaching, the ground would look like ripples on a  
body of water . The effect as Rayleigh waves pass is like  
standing on a boat deck in a choppy sea . 

Common Characteristics of Waves 

All waves, whether mechanical or electromagnetic, exhibit the measurable characteristics of wavelength, frequency, velocity, and amplitude. Wavelength refers to the linear distance between two identical points on the wave such as the distance between two crests or two compressions. The number of wavelengths that pass a point in a given amount of time (usually one second) is the wave’s frequency (f).Frequency is measured in hertz (Hz), with one hertz equal to one wave passing by in one second. 

The speed (v) of a wave is a measure of how quickly the wave’s disturbance travels through the medium or through empty space. The speed can be found by multiplying the wave’s frequency by its wavelength. This speed is always a constant for a given medium if the conditions such as temperature and pressure remain the same. 

v = fλ 

wave speed (m/s); frequency (Hz); wavelength (m) The amplitude of a wave is a measure of its displacement from the resting position. Amplitude indicates the energy of the wave. A sound wave with a larger amplitude creates a louder sound. Interactions between waves can affect their amplitude. Waves with the same wavelength that have synchronized crests or compressions are said to be in phase. When two in-phase waves coincide, the resulting merged wave has the sum of the two original amplitudes. This interaction is termed constructive interference. 

It is also possible for two waves to merge that have the same wavelength but opposite phase. In this case, one wave’s crests (or compressions) are aligned with the other wave’s troughs (or rarefactions). These out-of-phase waves may merge and cancel each other, forming a new wave with zero amplitude. When this destructive interference occurs with sound waves, the result is no sound. Noise-canceling headphones make use of destructive interference. 
